## Exercício 1: Vestibular

Considere que a os dados gerados na célula abaixo contêm o número de acertos de 100 alunos em um vestibular para um curso de exatas, divididas pelos respectivos assuntos. Considere que cada assunto possui um número de questões conforme a tabela abaixo:

| assunto | número de questões |
|:---:|:---:|
| Matemática | 24 |
| Português | 18 |
| Geografia | 8 |
| Inglês | 8 |
| História | 8 |
| Física | 12 |
| Química | 12 |

Usando os comandos de operações com DataFrames que você aprendeu na Aula 03, calcule:

1. (operações com escalar) Calcule o percentual de acerto dos alunos por assunto.  
2. (operações entre *DataFrames) Calcule o total de acertos de cada aluno.  
3. Calcule o porcentual geral de cada aluno.  
4. Suponha que a nota de corte para a segunda fase seja 45. Quantos alunos tiveram nota maior que 45?

In [1]:
import pandas as pd
import numpy as np

np.random.seed(42)
df_mat = pd.DataFrame(np.random.randint(24, size=(100, 1)), columns=['Qt_acertos'])

df_por = pd.DataFrame(np.random.randint(18, size=(100, 1)), columns=['Qt_acertos'])

df_geo = pd.DataFrame(np.random.randint(8, size=(100, 1)), columns=['Qt_acertos'])

df_ing = pd.DataFrame(np.random.randint(8, size=(100, 1)), columns=['Qt_acertos'])

df_his = pd.DataFrame(np.random.randint(8, size=(100, 1)), columns=['Qt_acertos'])

df_fis = pd.DataFrame(np.random.randint(12, size=(100, 1)), columns=['Qt_acertos'])

df_qui = pd.DataFrame(np.random.randint(12, size=(100, 1)), columns=['Qt_acertos'])

In [2]:
# 1) Seu código aqui

pc_mat = df_mat / 24
pc_por = df_por / 18
pc_geo = df_geo /  8
pc_ing = df_ing /  8
pc_his = df_his /  8
pc_fis = df_fis /  8
pc_qui = df_qui /  8

pc_mat

    Qt_acertos
0     0.250000
1     0.791667
2     0.583333
3     0.416667
4     0.291667
..         ...
95    0.250000
96    0.333333
97    0.958333
98    0.000000
99    0.458333

[100 rows x 1 columns]

In [3]:
# 2) Seu código aqui
total = df_mat + df_por + df_geo + df_ing + df_his + df_fis + df_qui
total

    Qt_acertos
0           35
1           48
2           50
3           32
4           30
..         ...
95          34
96          27
97          40
98          40
99          42

[100 rows x 1 columns]

In [4]:
# 3) Seu código aqui
total/90

    Qt_acertos
0     0.388889
1     0.533333
2     0.555556
3     0.355556
4     0.333333
..         ...
95    0.377778
96    0.300000
97    0.444444
98    0.444444
99    0.466667

[100 rows x 1 columns]

In [5]:
# 4) Seu código aqui
total_gt_45 = total[total['Qt_acertos'] > 45]
total_gt_45.count()

Qt_acertos    31
dtype: int64

## 2) Vestibular II

Ainda sobre o mesmo banco de dados:

1. Neste vestibular, quem 'zera' em matemática, física ou química está desqualificado. Monte um novo *DataFrame* com os alunos desqualificados por este critério.
2. Quantos são esses alunos?
3. Qual a média desses alunos em história e geografia?
4. Monte um *DataFrame* com os alunos que passaram para a segunda fase. Repare que estes alunos não podem ter sido desqualificados.

In [6]:
# seu código aqui
df_eliminados = total[(df_mat['Qt_acertos'] == 0) | 
                      (df_fis['Qt_acertos'] == 0) | 
                      (df_qui['Qt_acertos'] == 0)]

df_eliminados

    Qt_acertos
3           32
6           29
10          31
12          42
14          31
20          53
25          27
26          40
27          50
33          39
35          48
49          19
56          39
65          24
66          31
72          50
73          37
74          39
84          26
89          63
92          40
94          25
98          40

In [7]:
df_eliminados.count()

Qt_acertos    23
dtype: int64

## 3) Vacinações no Acre
Vamos trabalhar agora com a base de vacinações no Acre. Para facilitar a sua vida, copiamos o link do arquivo na célula abaixo.

1. Quantas vacinas estão registradas nessa base?  
2. Quantos pacientes foram vacinados? (considere um paciente para cada valor único de ```paciente_id```)  
3. Quantos pacientes únicos tomaram a primeira dose? OBS: Há um caractere especial neste campo. Receba os valores do campo com o método ```.unique()```.   
4. Quantos pacientes com menos de 18 anos foram vacinados?  
5. Quantos estabelecimentos aplicaram vacina no Acre?


**OBS:** O portal do DATASUS pode apresentar instabilidades, retornando um erro na segunda célula abaixo. Por este motivo está disponível uma base estática, que se for baixada para o seu *working directory* pode ser lida com este comando: ```df = pd.read_csv('registros de vacinacao covid ACRE.csv', sep=';')```.

**OBS2:** Para saber qual é o seu working directory, rode no jupyter: ```!pwd```.

In [39]:
arquivo = 'https://s3.sa-east-1.amazonaws.com/ckan.saude.gov.br/SIPNI/COVID/uf/uf%3DAC/part-00000-cf8a3eb4-ce59-45fd-a6c6-b858c45aec52.c000.csv'

In [40]:
# 1) Sua solução aqui
df = pd.read_csv(arquivo, sep=';')

C:\Users\raise\AppData\Local\Temp\ipykernel_5448\2145173094.py:2: DtypeWarning: Columns (7,8) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(arquivo, sep=';')

In [41]:
df.head()

,document_id,paciente_id,paciente_idade,paciente_dataNascimento,paciente_enumSexoBiologico,paciente_racaCor_codigo,paciente_racaCor_valor,paciente_endereco_coIbgeMunicipio,paciente_endereco_coPais,paciente_endereco_nmMunicipio,...,vacina_categoria_codigo,vacina_categoria_nome,vacina_lote,vacina_fabricante_nome,vacina_fabricante_referencia,vacina_dataAplicacao,vacina_descricao_dose,vacina_codigo,vacina_nome,sistema_origem
0,9c40bdcd-78df-42a2-baba-df6b6d8d2b40-i0b0,ed43984d7c86535e9493f652ae24f5c13049b6d497766e...,12,2009-12-21,F,3,PARDA,120020,10,CRUZEIRO DO SUL,...,2.0,Faixa Etária,FF8848,PFIZER,Organization/28290,2022-02-24,2ª Dose,87,COVID-19 PFIZER - COMIRNATY,Novo PNI
1,55760813-1f1e-46d4-a81c-c5c8b6dd98f4-i0b0,9a7c379aec2c44db0afd999e9bbf0d941b3314f20190e4...,58,1963-07-06,M,4,AMARELA,120040,10,RIO BRANCO,...,8.0,Trabalhadores da Educação,21OVCD317W,ASTRAZENECA/FIOCRUZ,149,2022-06-19,2º Reforço,85,COVID-19 ASTRAZENECA/FIOCRUZ - COVISHIELD,Novo PNI
2,589a58e5-cb43-4b14-bfb1-6056075f1abd-i0b0,bc865354f3526b281a6aea7f5ea26f9fb2354198b72fb0...,33,1987-11-08,M,4,AMARELA,110020,10,PORTO VELHO,...,2.0,Faixa Etária,217VCD231W,ASTRAZENECA/FIOCRUZ,Organization/33781055000135,2021-09-21,2ª Dose,85,COVID-19 ASTRAZENECA/FIOCRUZ - COVISHIELD,Novo PNI
3,5606aed0-0ad9-450e-ab5b-b60533a8d909-i0b0,9ef7008f1cbef9ebfd059a506a366743be20071bdd1ea3...,10,2011-03-27,F,3,PARDA,120030,10,FEIJO,...,NaN,NaN,FP1176,PFIZER,Organization/28290,2022-01-27,1ª Dose,87,COVID-19 PFIZER - COMIRNATY,Novo PNI
4,9b267040-9b24-4789-8b72-31d55ef218b4-i0b0,9031406559140e063863a282a2e3f4fdd5883e0c41b78a...,49,1972-04-20,F,3,PARDA,120038,10,PLACIDO DE CASTRO,...,1.0,Comorbidades,214VCD053W,ASTRAZENECA/FIOCRUZ,Organization/33781055000135,2021-07-23,2ª Dose,85,COVID-19 ASTRAZENECA/FIOCRUZ - COVISHIELD,Novo PNI

In [42]:
df.shape[0]

351215

In [43]:
# 2) 
df['paciente_id'].nunique()

293252

In [44]:
# 3) 
primeira_dose = df['vacina_descricao_dose'].unique()[0]
df['paciente_id'].loc[df['vacina_descricao_dose'] == primeira_dose].nunique()

117338

In [45]:
# 3) solução alternativa
primeira_dose = df['vacina_descricao_dose'].unique()[0]
df_primeira_dose = df[df['vacina_descricao_dose'] == primeira_dose]
df_primeira_dose['paciente_id'].nunique()

117338

In [46]:
# 4) 
df_menor = df[df["paciente_idade"]<18]
df_menor['paciente_id'].nunique()

55454

In [47]:
# 5)
df['estabelecimento_razaoSocial'].nunique()

51

## 4) Vacinação II
Gere um *DataFrame* que contenha somente os estabelecimentos que aplicaram vcinas a menores de 18 anos. Nesse *DataFrame* devem conter somente os dados dos estabelecimentos, mais uma coluna sendo a quantidade de vacinas que o estabelecimento aplicou a menores de 18 anos.  
  
1. crie uma cópia do *DataFrame* original, contendo somente os registros de vacinas realizadas a menores de 18 anos.  
2. crie uma lista das colunas desse *DataFrame* com o atributo de *DataFrame* **.columns()**  
3. Nesse *DataFrame* faça uma contagem do campo ```vacina_categoria_nome```.
3. a partir da lista de colunas, escolha somente aquelas que são referentes ao estabelecimento, faça uma lista com esses valores.  
4. usando o método *.loc*, selecione somente essas variáveis  
5. Aplique o método **.drop_duplicates** e crie uma lista com uma linha para cada estabelecimento, com os dados do estabelecimento

In [48]:
# 1) 
df_menor = df[df["paciente_idade"]<18].copy()

In [49]:
# 2)
df_menor.columns

Index(['document_id', 'paciente_id', 'paciente_idade',
       'paciente_dataNascimento', 'paciente_enumSexoBiologico',
       'paciente_racaCor_codigo', 'paciente_racaCor_valor',
       'paciente_endereco_coIbgeMunicipio', 'paciente_endereco_coPais',
       'paciente_endereco_nmMunicipio', 'paciente_endereco_nmPais',
       'paciente_endereco_uf', 'paciente_endereco_cep',
       'paciente_nacionalidade_enumNacionalidade', 'estabelecimento_valor',
       'estabelecimento_razaoSocial', 'estalecimento_noFantasia',
       'estabelecimento_municipio_codigo', 'estabelecimento_municipio_nome',
       'estabelecimento_uf', 'vacina_grupoAtendimento_codigo',
       'vacina_grupoAtendimento_nome', 'vacina_categoria_codigo',
       'vacina_categoria_nome', 'vacina_lote', 'vacina_fabricante_nome',
       'vacina_fabricante_referencia', 'vacina_dataAplicacao',
       'vacina_descricao_dose', 'vacina_codigo', 'vacina_nome',
       'sistema_origem'],
      dtype='object')

In [50]:
# 3)
df_menor['vacina_categoria_nome'].value_counts()

Faixa Etária                                      34834
Outros                                             3701
Povos Indígenas                                    1994
Povos e Comunidades Tradicionais                    616
Trabalhadores de Saúde                              238
População Privada de Liberdade                       50
Comorbidades                                         39
Gestantes                                            23
Pessoas com Deficiência                               4
Pessoas Institucionalizadas                           3
Pessoas de 60 anos ou mais institucionalizadas        1
Trabalhadores da Educação                             1
Name: vacina_categoria_nome, dtype: int64

In [51]:
# 4)
lista_variaveis = ['estabelecimento_valor',
       'estabelecimento_razaoSocial', 'estalecimento_noFantasia',
       'estabelecimento_municipio_codigo', 'estabelecimento_municipio_nome',
       'estabelecimento_uf']
df_menor_lista = df_menor.loc[:,lista_variaveis]

In [52]:
# 5)
df_menor_lista = df_menor_lista.drop_duplicates()
df_menor_lista.shape

(116, 6)

In [53]:
df_menor.head()

,document_id,paciente_id,paciente_idade,paciente_dataNascimento,paciente_enumSexoBiologico,paciente_racaCor_codigo,paciente_racaCor_valor,paciente_endereco_coIbgeMunicipio,paciente_endereco_coPais,paciente_endereco_nmMunicipio,...,vacina_categoria_codigo,vacina_categoria_nome,vacina_lote,vacina_fabricante_nome,vacina_fabricante_referencia,vacina_dataAplicacao,vacina_descricao_dose,vacina_codigo,vacina_nome,sistema_origem
0,9c40bdcd-78df-42a2-baba-df6b6d8d2b40-i0b0,ed43984d7c86535e9493f652ae24f5c13049b6d497766e...,12,2009-12-21,F,3,PARDA,120020,10,CRUZEIRO DO SUL,...,2.0,Faixa Etária,FF8848,PFIZER,Organization/28290,2022-02-24,2ª Dose,87,COVID-19 PFIZER - COMIRNATY,Novo PNI
3,5606aed0-0ad9-450e-ab5b-b60533a8d909-i0b0,9ef7008f1cbef9ebfd059a506a366743be20071bdd1ea3...,10,2011-03-27,F,3,PARDA,120030,10,FEIJO,...,NaN,NaN,FP1176,PFIZER,Organization/28290,2022-01-27,1ª Dose,87,COVID-19 PFIZER - COMIRNATY,Novo PNI
11,5659325a-aa5f-4831-8197-dbe613578b33-i0b0,5a4802dd8ef831d76f82369efa000ab9ee4e1ce62350d7...,13,2008-07-15,M,99,SEM INFORMACAO,120050,10,SENA MADUREIRA,...,2.0,Faixa Etária,FD7207,PFIZER,Organization/00394544000851,2021-09-01,1ª Dose,87,COVID-19 PFIZER - COMIRNATY,Novo PNI
12,c9a3de3c-2242-4c90-9ff3-b7091648f124-i0b0,8da7acc1657997f5855a393d568472aa43d567a69b4406...,10,2011-09-13,F,4,AMARELA,120033,10,MANCIO LIMA,...,NaN,NaN,FP8290,Pendente Identificação,Organization/28290,2022-01-25,1ª Dose,99,COVID-19 PEDIÁTRICA - PFIZER COMIRNATY,Novo PNI
26,80daae87-ac6a-4869-8a2a-a37fc48bb100-i0b0,ec7ead6b745849c4fcf25973adfa6470d1135b9a81ff60...,13,2009-01-01,M,99,SEM INFORMACAO,120020,10,CRUZEIRO DO SUL,...,7.0,Povos Indígenas,210520,SINOVAC/BUTANTAN,29501,2022-07-15,Reforço,86,COVID-19 SINOVAC/BUTANTAN - CORONAVAC,Novo PNI